Add error checking

diff --git a/bin/Software/screenshot b/bin/Software/screenshot
--- a/bin/Software/screenshot
+++ b/bin/Software/screenshot
@@ -11,12 +11,16 @@ fi
 sleep 1
 
 printf "SCREENSHOT: select region" > $TEMPFILE
-scrot -s $SCREENSHOT_NAME'.png'  -q 100 -c
+scrot -s $SCREENSHOT_NAME'.png' -q 100 -c
 
 printf "SCREENSHOT: uploading" > $TEMPFILE
 puush $SCREENSHOT_NAME.png
 
-printf "SCREENSHOT: done" > $TEMPFILE
-sleep $SLEEP
+if [[ $? != 0 ]]; then
+	printf "SCREENSHOT: failed to upload file (error $?)" > $TEMPFILE
+else
+	printf "SCREENSHOT: done" > $TEMPFILE
+fi
 
+sleep $SLEEP
 rm $SCREENSHOT_NAME.png $TEMPFILE
